name: CI to Docker hub

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Build and push latest
          id: docker_build_latest
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: sebader/locust-with-plugins:latest

        - name: Build and push specific
          id: docker_build_specific
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: sebader/locust-with-plugins:${{ github.run_id }}

        - name: Image digest
          run: echo ${{ steps.docker_build_latest.outputs.digest }}